# Generated by Django 4.1.3 on 2023-01-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups_app', '0005_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='organizer_email',
        ),
        migrations.AlterField(
            model_name='meetup',
            name='participants',
            field=models.ManyToManyField(blank=True, to='meetups_app.participant'),
        ),
    ]
