# Generated by Django 4.1.3 on 2023-01-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups_app', '0006_remove_meetup_date_remove_meetup_organizer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
