# Generated by Django 4.1.3 on 2023-01-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups_app', '0007_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='test@test.pl', max_length=254),
            preserve_default=False,
        ),
    ]
